In [ ]:
import numpy as np

# 4x3 행렬
A = np.array([
  [1, -1, 2],
  [3, 2, 2],
  [4, 1, 2],
  [7, 5, 6]
])

A

array([[ 1, -1,  2],
       [ 3,  2,  2],
       [ 4,  1,  2],
       [ 7,  5,  6]])

In [4]:
# 3x2 행렬
B = np.array([
  [1, -1],
  [3, 2],
  [4, 1]
])

B

array([[ 1, -1],
       [ 3,  2],
       [ 4,  1]])

In [ ]:
# 랜덤값을 행렬값으로 만드는 방법 MxN
C = np.random.rand(3, 5)
C

array([[0.07946176, 0.00546   , 0.01111354, 0.90186593, 0.84312236],
       [0.82483571, 0.92854251, 0.71669588, 0.20484808, 0.37944746],
       [0.21405866, 0.3482116 , 0.33465978, 0.04828647, 0.0543368 ]])

In [9]:
# 0으로만 이루어진 MxN행렬
D = np.zeros((2, 4))
D

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
A[0][2]

np.int64(2)

In [22]:
# 1: 행렬 A를 정의해보세요
A = np.array([
[ 0,  1, -1],
 [ 1,  2,  3],
 [ 2,  1,  0],
 [-1,  2,  -4]
 ])

# 2: 행렬 B를 정의해보세요
B = np.array([
 [ 0 , 2],
 [ 1 , 1],
 [-1, -2]
])

A[1][1]
A[3][1]

np.int64(2)

In [ ]:
A = np.array([
  
[
1
2
−
1
1
1
−
3
]
+
[
3
2
−
2
−
1
2
1
]
=
[
a
11
a
12
a
13
a
21
a
22
a
23
]
[ 
1
1
​
  
2
1
​
  
−1
−3
​
 ]
])