In [9]:
print('hello world! jupyter')

hello world! jupyter


In [10]:
print('my first project!')

my first project!


In [11]:
# 같은 세션에 있으면 선언된 함수나 변수를 사용할 수 있다.
x = 5
y = 10
print(x)
print(y)

5
10


In [12]:
print(x * y)

50


In [13]:
print(x)
print(y)

5
10


In [14]:
# 맨 마지막 줄에 결과값만 화면에 노출됨
x
y

10

In [15]:
y = 15
z = 30

데이터 사이언스

# 마크다운은 글을 깔끔하게 작성해주는 방법

In [1]:
# 데이터 사이언스 다양한 각도로 살펴보고 데이터를 인사이트를 찾아내는 작업
# NumPy = Numerical Python : 수치적인 연산에 최척화된 파이썬 도구
# Numpy Array = Python List
# 메모리 최적화, 연산 최적화가 되어있다.
import numpy as np

In [ ]:
array1 = np.array([1,3,5,7,9,11])
# 다차원 array
array2 = np.array([[2,3,5,6,7], [2,3,5,6,7], [2,3,5,6,7]])
array3 = np.zeros(5)
array4 = np.arange(10)
array2

array([[2, 3, 5, 6, 7],
       [2, 3, 5, 6, 7],
       [2, 3, 5, 6, 7]])

In [11]:
array1.size

6

In [14]:
array2.size
# 모양을 알려주는 변수: x * y의 다차원 array 갯수
array2.shape

(3, 5)

In [30]:
gdp_array = np.array([6610, 7637, 8127, 8885, 10385, 12565, 13403, 12398, 8282, 10672])
bitcoin_array = np.array([970, 1180, 1072, 1348, 2286, 2481,
                          2875, 4703, 4339, 6468, 10234, 14156])

bitcoin_array[[6,7,8]]
bitcoin_array[6:9]

array([2875, 4703, 4339])

In [34]:
# 세로줄 row, 가로줄 colum
gdp_array = np.array([
    [12257, 11561, 13165, 14673, 16496, 19403],  # 대한민국
    [39169, 34406, 32821, 35387, 38299, 37813],  # 일본
    [959, 1053, 1149, 1289, 1509, 1753],         # 중국
    [36335, 37133, 38023, 39496, 41713, 44115]   # 미국
])

gdp_array[1]

array([39169, 34406, 32821, 35387, 38299, 37813])

In [37]:
gdp_array[1][3]
gdp_array[1,3]

np.int64(35387)

In [46]:
# 앞쪽은 row 뒷쪽은 컬럼
gdp_array[:, 2:5]
gdp_array[:3, 2:5]

array([[13165, 14673, 16496],
       [32821, 35387, 38299],
       [ 1149,  1289,  1509]])

In [52]:
bitcoin_array = np.array([[970, 1180, 1072, 1348, 2286, 2481,
						   2875, 4703, 4339, 6468, 10234, 14156],
						  [514, 428, 1087, 976, 3426, 4448,
						   3262, 6355, 5570, 5801, 14074, 41034]])

bitcoin_array[1][6]
bitcoin_array[1:, 6][0]

np.int64(3262)

In [ ]:
# array bools 인덱스 or mask
gdp_array = np.array([6610, 7637, 8127, 8885, 10385, 12565, 13403, 12398, 8282, 10672])

gdp_array > 10000

array([False, False, False, False,  True,  True,  True,  True, False,
        True])

In [56]:
# True가 있는 인덱스만 받아와서 넣어준다.
mask = gdp_array > 10000
gdp_array[mask]

array([10385, 12565, 13403, 12398, 10672])

In [60]:
mask = (gdp_array > 10000) | (gdp_array < 8000)
gdp_array[mask]

array([ 6610,  7637, 10385, 12565, 13403, 12398, 10672])

In [ ]:
# 1부터 100까지 숫자가 들어 있는 numbers_array에서 짝수에 해당하는 숫자들만 뽑아 보세요!
# arange: 1 ~ 100까지 만들어주는 함수
numbers_array = np.arange(1, 101)
numbers_array[numbers_array % 2 == 0]
numbers_array


array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])